import Link from "next/link";
import { EmptyState, Notice, PageHeader, Panel } from "@/components/ui";
import { NewReportForm } from "@/components/reports/NewReportForm";
import { DeleteReportButton } from "@/components/reports/ReportControls";
import { fmtDate } from "@/lib/format";
import { monthKey, periodLabel } from "@/lib/period";
import { db } from "@/server/db";
import { getEarliestMonth, getLatestMonth, getStores } from "@/server/queries";
import { canWrite, requireOrg } from "@/server/session";

export const metadata = { title: "Reports" };

export default async function ReportsPage() {
  const ctx = await requireOrg();
  const [reports, stores, earliest, latest] = await Promise.all([
    db.report.findMany({ where: { organizationId: ctx.orgId }, include: { createdBy: { select: { name: true } } }, orderBy: { createdAt: "desc" } }),
    getStores(ctx.orgId),
    getEarliestMonth(ctx.orgId),
    getLatestMonth(ctx.orgId),
  ]);
  const writer = canWrite(ctx.role);

  return (
    <>
      <PageHeader
        title="Reports"
        subtitle="Print-ready documents assembled from recorded data. Every sentence is generated by fixed rules from the numbers; nothing is written freehand."
      />
      <div className="grid items-start gap-4 xl:grid-cols-[minmax(0,3fr)_minmax(0,2fr)]">
        <Panel title="Reports" subtitle={reports.length > 0 ? `${reports.length} saved` : undefined} flush>
          {reports.length === 0 ? (
            <div className="p-3">
              <EmptyState title="No reports yet">Create a report with the form{writer ? "" : " (requires owner or analyst role)"}. It can be printed or saved as PDF.</EmptyState>
            </div>
          ) : (
            <div className="scroll-thin overflow-x-auto">
              <table className="tbl min-w-[560px]">
                <thead>
                  <tr><th>Title</th><th>Period</th><th>Stores</th><th>Created</th><th>By</th>{writer && <th><span className="sr-only">Actions</span></th>}</tr>
                </thead>
                <tbody>
                  {reports.map((r) => (
                    <tr key={r.id}>
                      <td className="min-w-[200px]"><Link href={`/reports/${r.id}`} className="font-medium hover:underline">{r.title}</Link></td>
                      <td className="num whitespace-nowrap">{periodLabel({ from: monthKey(r.periodStart), to: monthKey(r.periodEnd) })}</td>
                      <td className="whitespace-nowrap">{r.storeIds.length === 0 ? "All" : <span className="num">{r.storeIds.length} selected</span>}</td>
                      <td className="num whitespace-nowrap">{fmtDate(r.createdAt)}</td>
                      <td className="whitespace-nowrap text-ink-2">{r.createdBy.name}</td>
                      {writer && <td className="text-right"><DeleteReportButton id={r.id} compact /></td>}
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </Panel>

        <Panel title="New report">
          {!writer ? (
            <Notice tone="unavailable" title="Read-only access">Your role cannot create reports.</Notice>
          ) : !earliest || !latest ? (
            <Notice tone="unavailable" title="No revenue data yet">
              A report covers a period of recorded data. <Link href="/stores" className="link">Add monthly data for a store</Link> first.
            </Notice>
          ) : (
            <NewReportForm earliest={earliest} latest={latest} stores={stores.map((s) => ({ id: s.id, name: s.name }))} />
          )}
        </Panel>
      </div>
    </>
  );
}
