import Link from "next/link";
import { CATEGORY_LABELS, STRATEGY_CATEGORIES } from "@/lib/strategy/library";
import type { StrategyCategoryKey } from "@/lib/strategy/rules";
import { getAIProvider } from "@/lib/providers/registry";
import { EmptyState, Notice, Tag } from "@/components/ui";
import { runAnalysis } from "@/server/actions/strategies";
import { first, type SearchParams } from "@/server/period";
import { getLatestMonth, getStores } from "@/server/queries";
import { ActionButton, QueryFilter } from "./ActionControls";
import { loadSignalSources, loadStrategies } from "./loaders";
import { StrategyCard } from "./StrategyCard";

export async function HypothesesTab({
  orgId, currency, canWrite, isDemo, sp,
}: { orgId: string; currency: string; canWrite: boolean; isDemo: boolean; sp: SearchParams }) {
  const [stores, latest] = await Promise.all([getStores(orgId), getLatestMonth(orgId)]);
  const storeParam = first(sp.store);
  const storeId = stores.some((s) => s.id === storeParam) ? storeParam : undefined;
  const categoryParam = first(sp.category);
  const category = (STRATEGY_CATEGORIES as string[]).includes(categoryParam ?? "") ? (categoryParam as StrategyCategoryKey) : undefined;
  const openId = first(sp.open);

  const [strategies, all] = await Promise.all([
    loadStrategies(orgId, { storeId, category }),
    storeId || category ? loadStrategies(orgId) : null,
  ]);
  const total = all ? all.length : strategies.length;
  const sources = await loadSignalSources(orgId, [...new Set(strategies.filter((s) => s.locationSignal && s.storeId).map((s) => s.storeId!))]);
  const ai = getAIProvider();
  const storeIds = stores.map((s) => s.id);

  return (
    <div className="space-y-3">
      <section className="rounded-md border border-line bg-surface p-3">
        <div className="grid items-start gap-x-6 gap-y-3 lg:grid-cols-[minmax(0,1fr)_minmax(0,22rem)]">
          <div className="min-w-0 max-w-3xl">
            <div className="flex flex-wrap items-center gap-2">
              <h2 className="text-[13px] font-semibold">Strategy engine</h2>
              {isDemo && <Tag kind="DEMO" />}
            </div>
            <p className="mt-1 text-ink-2">
              {ai
                ? `Hypotheses are generated by a deterministic rule engine from your data. A language model (${ai.info.label}) may rephrase the wording; it does not change any number.`
                : "Hypotheses are generated by a deterministic rule engine from your data. No language model is connected."}
            </p>
            <p className="mt-1 text-xs text-ink-3">
              Each rule compares a store with its own history or with your other stores and stays silent when the data it needs is missing.
              A difference between stores is a correlation, not a cause — every card is an idea to test, not a recommendation.
            </p>
          </div>
          {canWrite && (
            <div className="lg:justify-self-end">
              <ActionButton action={runAnalysis} className="btn-primary" pendingLabel="Analysing…" feedback="block">
                Run analysis
              </ActionButton>
              <p className="mt-1 text-2xs text-ink-3">
                Re-reads all stores{latest ? ` (data to ${latest})` : ""}. Hypotheses still in “Hypothesis” status are refreshed; others are kept.
              </p>
            </div>
          )}
        </div>
      </section>

      <div className="flex flex-wrap items-end justify-between gap-3">
        <QueryFilter
          basePath="/strategies"
          params={{ tab: "hypotheses" }}
          filters={[
            { name: "store", label: "Store", value: storeId ?? "", allLabel: "All stores", options: stores.map((s) => ({ value: s.id, label: s.name })) },
            { name: "category", label: "Category", value: category ?? "", allLabel: "All categories", options: STRATEGY_CATEGORIES.map((c) => ({ value: c, label: CATEGORY_LABELS[c] })) },
          ]}
        />
        <p className="text-xs text-ink-3">
          <span className="num">{strategies.length}</span> of <span className="num">{total}</span> hypotheses · sorted by store name, then oldest first — no ranking or score is applied
        </p>
      </div>

      {stores.length === 0 ? (
        <EmptyState title="No stores yet" action={<Link className="btn-primary" href="/stores/new">Add a store</Link>}>
          The rule engine needs at least one store with monthly data.
        </EmptyState>
      ) : strategies.length === 0 ? (
        total === 0 ? (
          <EmptyState title="No hypotheses yet">
            {latest
              ? "Run the analysis to let the rules look at your data, or write a hypothesis yourself. If no rule fires, the engine says so instead of inventing one."
              : "There is no monthly data yet. Enter monthly revenue for your stores, then run the analysis."}
          </EmptyState>
        ) : (
          <EmptyState title="No hypotheses match this filter" action={<Link className="btn-secondary" href="/strategies?tab=hypotheses">Clear filters</Link>}>
            {`${total} hypothes${total === 1 ? "is exists" : "es exist"} for other stores or categories.`}
          </EmptyState>
        )
      ) : (
        <div className="space-y-2">
          {strategies.map((s) => (
            <StrategyCard
              key={s.id}
              strategy={s}
              currency={currency}
              canWrite={canWrite}
              latestMonth={latest}
              signalSources={(s.storeId && sources.get(s.storeId)) || []}
              compareStoreIds={storeIds}
              defaultOpen={s.id === openId}
            />
          ))}
        </div>
      )}

      {!latest && stores.length > 0 && (
        <Notice tone="unavailable" title="No monthly data on file">Rules cannot run without monthly revenue data.</Notice>
      )}
    </div>
  );
}
